
server:  port: 8200
 
spring:
  datasource:
    username: root
    password: "006633"
    url: jdbc:mysql://localhost:3306/hotelmanagerment?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
 
mybatis:
  mapper-locations: classpath:mapping/**/*.xml
  type-aliases-package: com.neusoft.ho.model
 
#showSql
logging:
  level:
     com.neusoft.ho: debug
    
 
